# Site settings
url: http://luhtonen.github.com
title: Eduard Luhtonen
author: Eduard Luhtonen
description: > # Eduard Luhtonen's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
email:

# Github repositories
github_username: luhtonen

# Twitter
twitter_username: eluhtonen

# Facebook
facebook_username: eduard.luhtonen

# LinkedIn
linkedin_username: eduardluhtonen

# Build settings
markdown: kramdown
